# Generated by Django 3.2.16 on 2023-03-31 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=20, unique=True, verbose_name='사용자 계정')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('profile_image', models.URLField(default='')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='닉네임')),
                ('fullname', models.CharField(max_length=20, verbose_name='이름')),
                ('studentNo', models.PositiveIntegerField(default=21, verbose_name='학번')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolId', to='account.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Freind',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('follower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='followerId', serialize=False, to='account.user')),
                ('followee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followeeId', to='account.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
