# Generated by Django 3.2.16 on 2023-03-31 12:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50, verbose_name='강의 이름')),
                ('professor', models.CharField(max_length=20, verbose_name='교수 성함')),
                ('classroom', models.CharField(max_length=20, verbose_name='수업실')),
                ('credit', models.PositiveIntegerField(verbose_name='학수번호')),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 3, 31, 21, 54, 31, 992765), verbose_name='수업 시간')),
                ('day', models.CharField(max_length=20, verbose_name='수업 날짜')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectureId', to='account.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='My_lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('is_show', models.BooleanField(default=False, verbose_name='친구 공개 여부')),
                ('grade', models.IntegerField(verbose_name='점수')),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylectureId', to='timetable.lecture')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylectureuserId', to='account.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('content', models.CharField(max_length=200, verbose_name='리뷰 내용')),
                ('timetable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewId', to='timetable.my_lecture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lecture_enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('timetable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectureenrollmentId', to='timetable.my_lecture')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
