# Generated by Django 3.2.16 on 2023-03-31 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='게시판 이름')),
                ('category', models.CharField(max_length=20, unique=True, verbose_name='카테고리')),
                ('bookmark', models.CharField(max_length=20, verbose_name='즐겨찾기')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardId', to='account.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=100, verbose_name='게시물 제목')),
                ('postcontent', models.CharField(max_length=100, verbose_name='본문')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='익명 여부')),
                ('like_cnt', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
                ('comment_cnt', models.PositiveIntegerField(default=0, verbose_name='댓글 수')),
                ('scrap_cnt', models.PositiveIntegerField(default=0, verbose_name='스크랩 수')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postId', to='board.board')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrappostId', to='board.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapuserId', to='account.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('file_name', models.CharField(max_length=500, verbose_name='파일 이름')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photoId', to='board.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverId', to='account.user')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderId', to='account.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('messagecontent', models.CharField(max_length=100)),
                ('message_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageId', to='board.message_room')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messasgepostId', to='board.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fixed_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='즐겨찾기 게시판 이름')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixedboardId', to='board.board')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('commentcontent', models.CharField(max_length=100)),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='익명 여부')),
                ('like_cnt', models.PositiveIntegerField(verbose_name='좋아요 수')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.comment')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentpostId', to='board.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentuserId', to='account.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
